### ISSUE TITLE
Problem with Travis

### ISSUE THREAD

**Issue by MichaelGregg** [cisc3130/docs#11]
@rivlev 
<img width="1041" alt="screen shot 2017-10-23 at 9 48 43 pm" src="https://user-images.githubusercontent.com/25493211/31921196-043f7bc2-b83c-11e7-9706-f3175a60e7d1.png">
It says i have no repositories.  I DID sync my account, and it still says this.
And when i click on CISC 3410: 
<img width="1059" alt="screen shot 2017-10-23 at 9 49 56 pm" src="https://user-images.githubusercontent.com/25493211/31921212-29c458e0-b83c-11e7-84f5-f9a7867a0afe.png">
What do i need to do to fix this?

**Comment by rivlev** [comment]
Please see cisc3130/2-list#2
