### ISSUE TITLE
@rivlev Cannot Access Homework#0 Repository on Travis CI

### ISSUE THREAD

**Issue by fshnaidman98** [cisc3130/docs#13]
@rivlev

I don't have access to this course's content on Travis CI, so I can't authorize a repository.
![screen shot 2018-01-30 at 13 53 20](https://user-images.githubusercontent.com/33728343/35585133-0fa504ec-05c5-11e8-88f7-5a98a6764423.png)

**Comment by rivlev** [comment]
Have you tried using the instructions [here](https://github.com/cisc3130/docs/blob/master/travis.md)

**Comment by lavihayem** [comment]
I have issue to find the path of the folder(i put my homework in)

**Comment by lavihayem** [comment]
I am referring to the Ist time i use the git
