### ISSUE TITLE
travis-ci using problem @rivlev

### ISSUE THREAD

**Issue by Albert0501** [cisc3130/docs#15]
@rivlev

I tried to use travis-ci and commit a cpp file to test.
However, it give me a failure, and the log shows:
"
$ g++ helloworld.cpp
g++: error: helloworld.cpp: No such file or directory
g++: fatal error: no input files
compilation terminated.
The command "g++ helloworld.cpp" exited with 4.
0.01s$ ./a.out
/home/travis/.travis/job_stages: line 57: ./a.out: No such file or directory
The command "./a.out" exited with 127.
Done. Your build exited with 1.
"
Any suggestions?

**Comment by rivlev** [comment]
Your repository has no files (.travis.yml and Readme.md were deleted, and helloworld.cpp was created and then deleted)

**Comment by Albert0501** [comment]
@rivlev
Really? But in the hw branch under my repository, there are three files, travis.yml, helloworld.cpp and Readme.md, listed. I can read and edit them. 
![1](https://user-images.githubusercontent.com/35945933/35646869-a9ef8e76-069e-11e8-8c03-dc79f900181f.png)

**Comment by Albert0501** [comment]
I found what cause the error:
the ".travis.yml" coded, "- g++ helloworld.cpp" but my file is Helloworld.cpp
The "H" causes the problem.
