### ISSUE TITLE
@rivlev Can’t automatically merge

### ISSUE THREAD

**Issue by Albert0501** [cisc3130/docs#17]
@rivlev
I tried to pull requests and when I click in and select master as base, hw as compare, the message "Can’t automatically merge" shows up.
Is it matter? Will it affect the pull requests?
Here is the screen cut picture:
![2](https://user-images.githubusercontent.com/35945933/35711200-ba5cf76c-0789-11e8-8a45-48cbf698a2cf.png)

**Comment by rivlev** [comment]
It should be okay but can be a signal that something was done incorrectly.
I only see one branch in your repository.
The pull request that you created and closed three days ago was correct. I restored the branch that was deleted. Enable travis, reopen the pull request, and put my @mention and your name in the body of the pull request.
