### ISSUE TITLE
Restarting from scratch

### ISSUE THREAD

**Issue by zeeshanmustafa** [cisc3130/docs#2]
I have done so many silly things such as made a branch and change the instruction in codes. As of now trying to clone/downlaod but I am having an error . Is it possible to start from scratch? @rivlev

Also I am not sure what terminal we are talking about as I never used it for C++ in KBCC we used it dev C++ compiler, so I am totally lost. I dont know how to clone a file in my machine and where to get the terminal from that would sync my github files into terminal. 
@rivlev

**Comment by rivlev** [comment]
Starting from scratch: git is set up to help you restart, as it saves the history of any changes. There are many different ways to do it. What probably would work best for you here is 

```git reset --hard 406a994```

which will *destructively* revert any changes made since commit #406a994 (my last commit).

and then commit

```git commit -m ''reverting to commit 406a904''```

Let me know if that works.

Reference: https://stackoverflow.com/questions/9529078/how-do-i-use-git-reset-hard-head-to-revert-to-a-previous-commit

Terminal -- I put this in a separate issue and answered it (issue #3)

**Comment by zeeshanmustafa** [comment]
I am not sure where to even write those commands. I dont even know what terminal to downlaod in my PC.
The main problem is I dont have terminal or command where i can clone my files from git hub and start writing down the codes. @rivlev .

**Comment by h01m3s** [comment]
**Before you start, find a git tutorial on Youtube to briefly understand how git and Github works.**

Commands are typed in terminal(MacOS/Linux) or Command Prompt(Windows).

Following are examples on MacOS:

1. Open terminal (Go to Launchpad and search for terminal):

2. Create a CISC 3410 Folder:
`mkdir CISC\ 3410`
Go to directory
`cd CISC\ 3410`

3. Clone Repository into local Machine:
`git clone https://github.com/cisc3130/0-get-started`
**Don't just clone this url, use the one that GitHub generated for your homework.**

4. You will now see a new Folder called "0-get-started-yourgithubname" inside your CISC 3410 folder.
Then go to your workspace (the folder that you just clone from GitHub)
`cd 0-get-started-yourgithubname`

5. Create a new branch:
`git checkout -b hw`

6. Then do what homework ask you to do.

7. After you finish your homework, add all changed file to repository and commit with a message
`git add .`
`git commit -m "message"`

8. Then push to remote repository and create a pull request.
`git push origin hw`

You can find more details here: [https://github.com/cisc3130/docs/blob/master/submissions.md](url)

There's still time to figure these out, and you can use a git GUI client. For example: **SourceTree**.
