### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by fhdalv** [cisc3130/docs#27]
Hello, I just modified the project file and committed all the changes to the hw branch in my local repo. But I tried to push it to the origin hw and it says permission denied. So what should be my next step?
@rivlev 

Regards
Alvi

**Comment by rivlev** [comment]
You don't have permission to push to the original repository (cisc3130/0-get-started)
You need to modify and push to the copy that github classroom made for you (cisc3130/0-get-started-fhdalv)
