### ISSUE TITLE
repository not found

### ISSUE THREAD

**Issue by Brendafried** [cisc3130/docs#4]
When I try to clone my remote repository, I get the  following: 
ERROR: Repository not found.
fatal: Could not read from remote repository.

how do I fix this?
@rivlev

**Comment by rivlev** [comment]
What command did you use? Did you paste in the url from your remote repository?

**Comment by Brendafried** [comment]
git clone --recursive (url from remote repository)
yes.
@rivlev

**Comment by rivlev** [comment]
git's documentation says one cause for this error is not having ssh access to a repository.
You can try working through [this](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/)

I've also seen that it can happen from a faulty Internet connection, so you can also try connectivity tricks like disconnecting from and reconnecting to wifi.

Please close if this works or bump up if it's still not working.
