### ISSUE TITLE
Submit the files to the public repository or the private?

### ISSUE THREAD

**Issue by dylancfe15** [cisc3130/docs#7]
The one has a title of "cisc3130/0-get-started" or the one has a title of "cisc3130/0-get-started+(Github name)"?

**Comment by dylancfe15** [comment]
The one has a title of "cisc3130/0-get-started" or the one has a title of "cisc3130/0-get-started+(Github name)"?

**Comment by h01m3s** [comment]
Private. 

"cisc3130/0-get-started+(Github name)"
